### ISSUE TITLE
Error when running siman analysis

### ISSUE THREAD

**Issue by JanDitzen** [UCL/siman#5]
I updated siman from GitHub and I obtain the error:

"C:\Users\JDitzen\ado\plus/s/simsum.ado is version 2.0.4 which is older than target 2.1.2"

when running siman analysis. Is there a problem with versions here?

**Comment by tpmorris** [comment]
Thanks! Simsum was updated on github but not SSC. We’ve now added an error msg to siman_analyse saying how to get the latest version of simsum from github.
